name: Setup tox test environments
description: 'Find all tox environments configured by "type"'

outputs:
  lint:
    description: JSON array of lint tox environments
    value: ${{ steps.envs.outputs.tox_lint_envs }}
  test:
    description: JSON array of test tox environments
    value: ${{ steps.envs.outputs.tox_test_envs }}

runs:
  using: "composite"
  steps:
    - id: envs
      shell: bash
      run: |
        if [ ! -f tox.ini ];
        then
          echo "No tox file found"
          exit
        fi

        tox_envs=$(tox --listenvs)

        tox_lint_envs=$(grep -Ev '^test(-|$)' <<< "$tox_envs" || true)
        if [ -n "$tox_lint_envs" ];
        then
        
          tox_lint_envs=$(jq -Rnc '[inputs]' <<< "$tox_lint_envs")
          echo "Found lint environments: $tox_lint_envs"

          echo "tox_lint_envs=$tox_lint_envs" >> $GITHUB_OUTPUT
        fi

        tox_test_envs=$(grep -E '^test(-|$)' <<< "$tox_envs" || true)
        if [ -n "$tox_test_envs" ];
        then
        
          tox_test_envs=$(jq -Rnc '[inputs]' <<< "$tox_test_envs")
          echo "Found test environments: $tox_test_envs"
        
          echo "tox_test_envs=$tox_test_envs" >> $GITHUB_OUTPUT
        fi
