name: Setup tox test environments

on:
  workflow_call:
    outputs:
      lint:
        description: JSON array of lint tox environments
        value: ${{ jobs.setup-tox-envs.outputs.lint }}
      test:
        description: JSON array of test tox environments
        value: ${{ jobs.setup-tox-envs.outputs.test }}

jobs:
  setup-tox-envs:
    runs-on: ubuntu-latest
    outputs:
      lint: ${{ steps.envs.outputs.lint }}
      test: ${{ steps.envs.outputs.test }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: infrabits/ci-setup-python@main
        with:
          install_dependencies: false
          install_test_dependencies: false
          install_tox: true

      - name: setup tox environments
        uses: infrabits/ci-setup-tox-envs@main
        id: envs
